# Generated by Django 2.2 on 2019-04-05 19:02

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hordak', '0025_auto_20180829_1605'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('transaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hordak.Transaction')),
                ('state', models.CharField(choices=[('pending', 'Pending'), ('complete', 'Complete'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('reference_data', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
            bases=('hordak.transaction',),
        ),
        migrations.CreateModel(
            name='Withdraw',
            fields=[
                ('transaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hordak.Transaction')),
                ('state', models.CharField(choices=[('pending', 'Pending'), ('complete', 'Complete'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('reference_data', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
            bases=('hordak.transaction',),
        ),
    ]
