# Generated by Django 2.2 on 2019-04-06 08:48

from django.db import migrations
import django.db.models.deletion
import river.models.fields.state


class Migration(migrations.Migration):

    dependencies = [
        ('hordak', '0026_deposit_withdraw'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='state',
            field=river.models.fields.state.StateField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rn47b4d1ec35e9447c8af06ec3b37941c2', to='river.State'),
        ),
        migrations.AlterField(
            model_name='withdraw',
            name='state',
            field=river.models.fields.state.StateField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rnb9a1c17936504612bea7a4bf03024a2e', to='river.State'),
        ),
    ]
