# Generated by Django 2.2 on 2019-04-06 08:49

from django.db import migrations
import django.db.models.deletion
import river.models.fields.state


class Migration(migrations.Migration):

    dependencies = [
        ('river', '0001_initial'),
        ('hordak', '0027_auto_20190406_0848'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deposit',
            name='state',
        ),
        migrations.RemoveField(
            model_name='withdraw',
            name='state',
        ),
        migrations.AddField(
            model_name='deposit',
            name='state_field',
            field=river.models.fields.state.StateField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rn1792e2e290d848bfaab5281504c3f446', to='river.State'),
        ),
        migrations.AddField(
            model_name='withdraw',
            name='state_field',
            field=river.models.fields.state.StateField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rn5d0afa9f3d4c45fabd22b3c8521217a8', to='river.State'),
        ),
    ]
