# Generated by Django 2.2 on 2019-04-06 09:07

from django.db import migrations, models
import django.db.models.deletion
import river.models.fields.state


class Migration(migrations.Migration):

    dependencies = [
        ('hordak', '0028_auto_20190406_0849'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='withdraw',
            name='amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=16),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='deposit',
            name='state_field',
            field=river.models.fields.state.StateField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rneadada06085e407091e7e7660e1f8e6c', to='river.State'),
        ),
        migrations.AlterField(
            model_name='withdraw',
            name='state_field',
            field=river.models.fields.state.StateField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rn5bd9d5a4bd194b2dbd32c3edc1f9fbf9', to='river.State'),
        ),
    ]
