# Generated by Django 2.2 on 2019-04-06 09:28

from django.db import migrations
import django.db.models.deletion
import river.models.fields.state


class Migration(migrations.Migration):

    dependencies = [
        ('hordak', '0031_auto_20190406_0922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='status',
            field=river.models.fields.state.StateField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rn56d6ca6656c948afa8818c4063cc0185', to='river.State'),
        ),
        migrations.AlterField(
            model_name='withdraw',
            name='status',
            field=river.models.fields.state.StateField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rnd9082edc10ee40bc97a2b568ce52d475', to='river.State'),
        ),
    ]
