# Generated by Django 2.2 on 2019-04-06 09:30

from django.db import migrations
import django.db.models.deletion
import river.models.fields.state


class Migration(migrations.Migration):

    dependencies = [
        ('hordak', '0032_auto_20190406_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='status',
            field=river.models.fields.state.StateField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rn06a70153fb824771bfcf94a58a176bf8', to='river.State'),
        ),
        migrations.AlterField(
            model_name='withdraw',
            name='status',
            field=river.models.fields.state.StateField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rnf14c937e88cf47a5872e050da37d0094', to='river.State'),
        ),
    ]
