# Generated by Django 2.0.13 on 2019-04-06 13:07

from django.db import migrations
import django.db.models.deletion
import django_smalluuid.models
import river.models.fields.state


class Migration(migrations.Migration):

    dependencies = [
        ('hordak', '0036_auto_20190406_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='uuid',
            field=django_smalluuid.models.SmallUUIDField(default=django_smalluuid.models.UUIDTypedDefault(type=1), editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='status',
            field=river.models.fields.state.StateField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rn701bb68bb67a4055858d35d25f80d5c0', to='river.State'),
        ),
        migrations.AlterField(
            model_name='leg',
            name='uuid',
            field=django_smalluuid.models.SmallUUIDField(default=django_smalluuid.models.UUIDTypedDefault(type=3), editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='statementimport',
            name='uuid',
            field=django_smalluuid.models.SmallUUIDField(default=django_smalluuid.models.UUIDTypedDefault(type=4), editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='statementline',
            name='uuid',
            field=django_smalluuid.models.SmallUUIDField(default=django_smalluuid.models.UUIDTypedDefault(type=5), editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='uuid',
            field=django_smalluuid.models.SmallUUIDField(default=django_smalluuid.models.UUIDTypedDefault(type=2), editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='withdraw',
            name='status',
            field=river.models.fields.state.StateField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rnbeb1cb24e7b94f698e452db5862bee55', to='river.State'),
        ),
    ]
