# Generated by Django 2.0.13 on 2019-04-06 13:46

from django.db import migrations
import django.db.models.deletion
import river.models.fields.state


class Migration(migrations.Migration):

    dependencies = [
        ('hordak', '0038_auto_20190406_1307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deposit',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='withdraw',
            name='amount',
        ),
        migrations.AlterField(
            model_name='deposit',
            name='status',
            field=river.models.fields.state.StateField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rn0cd10b9e0f1b4e30abbc61313b1d22c7', to='river.State'),
        ),
        migrations.AlterField(
            model_name='withdraw',
            name='status',
            field=river.models.fields.state.StateField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rn04d5f4d396b24b6c9242e685e73432bf', to='river.State'),
        ),
    ]
